"""
Infrastructure: NLP enrichment pipeline.

Two-stage classifier:
  1. Baseline – keyword/rule-based classifier (fast, no training needed).
  2. ML classifier – TF-IDF + LogisticRegression trained on weak labels
     generated by the baseline (auto-trains if no model file exists).

Sentiment: VADER (over TextBlob) because:
  - Specifically tuned for short news headlines / social text.
  - No external corpus download required at runtime.
  - Compound score maps cleanly to positive/neutral/negative.

Entity extraction: lightweight regex heuristic (capitalised phrases) to
avoid the ~40 MB spaCy model download requirement for MVP.
Replace with spaCy for production.
"""
from __future__ import annotations

import logging
import pickle
import re
from pathlib import Path
from typing import Optional

from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

from src.domain.interfaces import NLPEnricher
from src.domain.models import Article, NewsCategory, Sentiment

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Category keyword rules
# ---------------------------------------------------------------------------

_RULES: dict[NewsCategory, list[str]] = {
    NewsCategory.GEOPOLITICS: [
        "war", "conflict", "military", "nato", "troops", "invasion", "sanctions",
        "missile", "ceasefire", "diplomacy", "UN", "united nations", "geopolitics",
        "coup", "ukraine", "russia", "israel", "gaza", "taiwan", "china",
        "north korea", "iran", "nuclear", "terrorism", "jihad",
    ],
    NewsCategory.ECONOMY: [
        "gdp", "inflation", "interest rate", "federal reserve", "fed", "ecb",
        "central bank", "recession", "unemployment", "stock market", "dow jones",
        "s&p 500", "nasdaq", "bond yield", "treasury", "debt", "deficit",
        "imf", "world bank", "trade war", "tariff", "currency", "forex",
        "crypto", "bitcoin", "etf", "earnings", "fiscal policy",
    ],
    NewsCategory.TECH_AI: [
        "artificial intelligence", "ai", "machine learning", "llm", "gpt",
        "openai", "anthropic", "google deepmind", "nvidia", "chip",
        "semiconductor", "tech giant", "big tech", "silicon valley",
        "cybersecurity", "hack", "data breach", "regulation", "antitrust",
        "social media", "meta", "apple", "microsoft", "amazon",
    ],
    NewsCategory.CLIMATE: [
        "climate change", "global warming", "carbon", "emissions", "cop",
        "renewable", "solar", "wind energy", "fossil fuel", "oil price",
        "natural gas", "drought", "flood", "wildfire", "ipcc",
        "net zero", "green energy", "electricity grid", "nuclear power",
    ],
    NewsCategory.HEALTH: [
        "pandemic", "covid", "vaccine", "who", "world health organization",
        "outbreak", "disease", "hospital", "healthcare", "mental health",
        "opioid", "drug approval", "fda", "obesity", "aging population",
        "fertility", "birth rate", "demographics",
    ],
    NewsCategory.CANADA: [
        "canada", "canadian", "ottawa", "toronto", "montreal", "québec",
        "bank of canada", "boc", "trudeau", "mark carney", "immigration",
        "cra", "healthcare canada", "opioid canada", "housing canada",
        "alberta", "ontario", "bc", "prairie", "arctic sovereignty",
        "francophone", "bilingualism", "rcmp",
    ],
}


def _build_keyword_index() -> dict[str, NewsCategory]:
    """Pre-compile lower-cased keyword → category lookup."""
    index: dict[str, NewsCategory] = {}
    for cat, keywords in _RULES.items():
        for kw in keywords:
            index[kw.lower()] = cat
    return index


_KW_INDEX = _build_keyword_index()

# Ordered priority so more specific categories win ties
_PRIORITY: list[NewsCategory] = [
    NewsCategory.CANADA,       # most specific first
    NewsCategory.GEOPOLITICS,
    NewsCategory.TECH_AI,
    NewsCategory.ECONOMY,
    NewsCategory.HEALTH,
    NewsCategory.CLIMATE,
]


def classify_keyword(text: str) -> tuple[NewsCategory, float]:
    """
    Rule-based classifier: count keyword hits per category.

    Returns:
        (category, confidence) where confidence ∈ [0, 1] derived from
        the fraction of total hits attributed to the winning category.
    """
    text_lower = text.lower()
    scores: dict[NewsCategory, int] = {cat: 0 for cat in NewsCategory}

    for kw, cat in _KW_INDEX.items():
        if kw in text_lower:
            scores[cat] += 1

    total_hits = sum(scores.values())
    if total_hits == 0:
        return NewsCategory.UNKNOWN, 0.0

    # Resolve ties by priority order
    max_score = max(scores.values())
    candidates = [cat for cat in _PRIORITY if scores[cat] == max_score]
    winner = candidates[0] if candidates else NewsCategory.UNKNOWN

    confidence = round(scores[winner] / total_hits, 3)
    return winner, confidence


# ---------------------------------------------------------------------------
# Simple entity extractor (heuristic – no spaCy dependency)
# ---------------------------------------------------------------------------

_ENTITY_RE = re.compile(r"\b([A-Z][a-z]+(?: [A-Z][a-z]+){0,3})\b")
_STOP_ENTITIES = {
    "The", "A", "An", "In", "On", "At", "By", "For", "To",
    "New", "This", "That", "These", "Those",
}


def extract_entities(text: str, max_entities: int = 10) -> list[str]:
    """
    Extract capitalised n-grams as named-entity candidates.
    Fast heuristic; replace with spaCy ner for production.
    """
    matches = _ENTITY_RE.findall(text)
    seen: dict[str, int] = {}
    for m in matches:
        if m not in _STOP_ENTITIES:
            seen[m] = seen.get(m, 0) + 1
    # Return most frequent first
    sorted_entities = sorted(seen, key=lambda x: -seen[x])
    return sorted_entities[:max_entities]


# ---------------------------------------------------------------------------
# Keyword extractor
# ---------------------------------------------------------------------------

_COMMON_WORDS = {
    "the", "a", "an", "and", "or", "but", "in", "on", "at", "to",
    "for", "of", "with", "by", "from", "is", "are", "was", "were",
    "be", "been", "being", "have", "has", "had", "do", "does", "did",
    "will", "would", "could", "should", "may", "might", "can", "that",
    "this", "it", "its", "as", "not", "no", "up", "out", "about",
    "after", "before", "new", "says", "said", "also", "more", "over",
}


def extract_keywords(title: str, summary: str, top_n: int = 8) -> list[str]:
    """Extract simple frequency-based keywords from title + summary."""
    text = f"{title} {summary}".lower()
    words = re.findall(r"\b[a-z]{4,}\b", text)
    freq: dict[str, int] = {}
    for w in words:
        if w not in _COMMON_WORDS:
            freq[w] = freq.get(w, 0) + 1
    return sorted(freq, key=lambda x: -freq[x])[:top_n]


# ---------------------------------------------------------------------------
# Sentiment
# ---------------------------------------------------------------------------

_vader = SentimentIntensityAnalyzer()


def score_sentiment(text: str) -> tuple[Sentiment, float]:
    """
    Score sentiment using VADER compound score.

    Returns:
        (Sentiment enum, compound score ∈ [-1, 1])
    """
    scores = _vader.polarity_scores(text)
    compound = scores["compound"]
    if compound >= 0.05:
        return Sentiment.POSITIVE, compound
    elif compound <= -0.05:
        return Sentiment.NEGATIVE, compound
    return Sentiment.NEUTRAL, compound


# ---------------------------------------------------------------------------
# ML classifier (TF-IDF + LogisticRegression trained on weak labels)
# ---------------------------------------------------------------------------

class MLClassifier:
    """
    Lightweight scikit-learn classifier trained on keyword-labelled articles.

    Automatically trains from the labelled corpus when no model file exists.
    Persists to disk via pickle for reuse across runs.

    Args:
        model_path: Where to persist / load the trained model.
    """

    def __init__(self, model_path: Path) -> None:
        self._model_path = model_path
        self._pipeline: Optional[object] = None
        self._load()

    def _load(self) -> None:
        if self._model_path.exists():
            try:
                with open(self._model_path, "rb") as fh:
                    self._pipeline = pickle.load(fh)
                logger.info("ML classifier loaded from %s", self._model_path)
            except Exception as exc:
                logger.warning("Could not load ML model: %s", exc)

    def train(self, texts: list[str], labels: list[str]) -> None:
        """Train the pipeline on (text, label) pairs and persist to disk."""
        from sklearn.linear_model import LogisticRegression
        from sklearn.pipeline import Pipeline
        from sklearn.feature_extraction.text import TfidfVectorizer

        if len(texts) < 20:
            logger.warning("Too few samples to train ML classifier (%d)", len(texts))
            return

        logger.info("Training ML classifier on %d samples", len(texts))
        pipe = Pipeline([
            ("tfidf", TfidfVectorizer(max_features=5000, ngram_range=(1, 2),
                                      sublinear_tf=True)),
            ("clf", LogisticRegression(max_iter=300, random_state=42,
                                       class_weight="balanced")),
        ])
        pipe.fit(texts, labels)
        self._pipeline = pipe
        self._model_path.parent.mkdir(parents=True, exist_ok=True)
        with open(self._model_path, "wb") as fh:
            pickle.dump(pipe, fh)
        logger.info("ML classifier saved to %s", self._model_path)

    def predict(self, text: str) -> tuple[str, float]:
        """
        Predict category label and confidence for a given text.

        Falls back to keyword classifier if no model is loaded.
        """
        if self._pipeline is None:
            cat, conf = classify_keyword(text)
            return cat.value, conf
        try:
            label = self._pipeline.predict([text])[0]
            proba = self._pipeline.predict_proba([text]).max()
            return label, float(proba)
        except Exception as exc:
            logger.warning("ML predict failed: %s", exc)
            cat, conf = classify_keyword(text)
            return cat.value, conf

    @property
    def is_trained(self) -> bool:
        return self._pipeline is not None


# ---------------------------------------------------------------------------
# Composite Enricher (implements NLPEnricher port)
# ---------------------------------------------------------------------------

class CompositeNLPEnricher(NLPEnricher):
    """
    Enriches an Article with:
    - Category (ML if available, else keyword rule)
    - Sentiment (VADER)
    - Named entities (heuristic)
    - Keywords (frequency)

    Args:
        ml_classifier: Optional ML classifier; uses keyword fallback if None.
        use_ml: If True and classifier is trained, use ML for classification.
    """

    def __init__(
        self,
        ml_classifier: Optional[MLClassifier] = None,
        use_ml: bool = True,
    ) -> None:
        self._ml = ml_classifier
        self._use_ml = use_ml

    def enrich(self, article: Article) -> Article:
        """Enrich article in-place and return it."""
        text = f"{article.title} {article.summary}"

        # Classification
        if self._use_ml and self._ml and self._ml.is_trained:
            cat_str, conf = self._ml.predict(text)
            try:
                article.category = NewsCategory(cat_str)
            except ValueError:
                article.category = NewsCategory.UNKNOWN
            article.category_confidence = conf
        else:
            article.category, article.category_confidence = classify_keyword(text)

        # Sentiment
        article.sentiment, article.sentiment_score = score_sentiment(
            article.title + " " + article.summary
        )

        # Entities & keywords
        article.entities = extract_entities(text)
        article.keywords = extract_keywords(article.title, article.summary)

        article.is_enriched = True
        return article
