"""
Application service: trains (or retrains) the ML classifier using
weak labels generated by the keyword baseline.

Designed to be run manually or scheduled (e.g., weekly).
"""
from __future__ import annotations

import logging
from pathlib import Path

from src.domain.interfaces import ArticleRepository
from src.infrastructure.nlp.enricher import MLClassifier, classify_keyword
from src.domain.models import NewsCategory

logger = logging.getLogger(__name__)

_MIN_SAMPLES = 50
_EXCLUDE = {NewsCategory.UNKNOWN}


class ModelTrainer:
    """
    Trains the ML classifier using articles stored in the repository.

    The weak labels come from the keyword classifier. Only articles with
    category != UNKNOWN are used to avoid noisy labels.

    Args:
        repository: Article storage source.
        model_path: Where to persist the trained model.
    """

    def __init__(self, repository: ArticleRepository, model_path: Path) -> None:
        self._repo = repository
        self._model_path = model_path

    def run(self) -> None:
        """Fetch labelled articles and train the classifier."""
        logger.info("Fetching articles for training...")
        articles = self._repo.get_all(limit=5000)
        texts, labels = [], []

        for article in articles:
            text = f"{article.title} {article.summary}"
            cat, conf = classify_keyword(text)
            if cat in _EXCLUDE or conf < 0.4:
                continue
            texts.append(text)
            labels.append(cat.value)

        if len(texts) < _MIN_SAMPLES:
            logger.warning(
                "Only %d labelled samples found (need %d). Skipping training.",
                len(texts), _MIN_SAMPLES,
            )
            return

        label_dist = {l: labels.count(l) for l in set(labels)}
        logger.info("Label distribution: %s", label_dist)

        clf = MLClassifier(self._model_path)
        clf.train(texts, labels)
        logger.info("Training complete.")
